# This file was generated by GoReleaser. DO NOT EDIT.
cask "network-doctor" do
  version "1.16.2"

  on_macos do
    on_intel do
      sha256 "be974309afdf120b3fcc1f9a7a76d353bf4ffaf3b926aa11b2b40c15b83352d7"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_darwin_amd64"
      binary "netdoc_1.16.2_darwin_amd64", target: "netdoc"
    end
    on_arm do
      sha256 "ee5c757bed684af2f2b5f844de77377c111cce2042c02321fe0cadd8b83953f5"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_darwin_arm64"
      binary "netdoc_1.16.2_darwin_arm64", target: "netdoc"
    end
  end

  on_linux do
    on_intel do
      sha256 "65962f9ac12d5725da70afc7be612c37eab0604ed890791c70eced23c0fb3e62"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_linux_amd64"
      binary "netdoc_1.16.2_linux_amd64", target: "netdoc"
    end
    on_arm do
      sha256 "a3104e7991e089bad1eadaf88666e3e12f574c6024152038a51f026ab74da908"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_linux_arm64"
      binary "netdoc_1.16.2_linux_arm64", target: "netdoc"
    end
  end

  name "network-doctor"
  desc "Terminal UI that diagnoses network connectivity and names the layer where the connection breaks"
  homepage "https://heymaikol.github.io/network-doctor/"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
