# This file was generated by GoReleaser. DO NOT EDIT.
cask "network-doctor" do
  version "1.10.0"

  on_macos do
    on_intel do
      sha256 "1fbffeda0895f8827f0135c596f1d946b1a4208aae7bda82b44252c54336d2f1"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_darwin_amd64"
      binary "netdoc_1.10.0_darwin_amd64", target: "netdoc"
    end
    on_arm do
      sha256 "7faed3918e4069b0dafc702e4ff0d972f5f1665e2a72986928612bf930ca24b0"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_darwin_arm64"
      binary "netdoc_1.10.0_darwin_arm64", target: "netdoc"
    end
  end

  on_linux do
    on_intel do
      sha256 "bccd8e8c57fd961558c8ab77478f1ee0817ae89329c8bfe3c34c7f5d9bd85a16"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_linux_amd64"
      binary "netdoc_1.10.0_linux_amd64", target: "netdoc"
    end
    on_arm do
      sha256 "f6650bae3c4857c507300f719917cfac2b2972ecd9248955ded5ca0af365bd59"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_linux_arm64"
      binary "netdoc_1.10.0_linux_arm64", target: "netdoc"
    end
  end

  name "network-doctor"
  desc "Terminal UI that diagnoses network connectivity and explains where the connection breaks"
  homepage "https://github.com/heymaikol/network-doctor"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
