# This file was generated by GoReleaser. DO NOT EDIT.
cask "network-doctor" do
  version "1.7.1"

  on_macos do
    on_intel do
      sha256 "98213964fc2c387748d47349910dd3046db62d3c217ecbfc862116a8cee4bd95"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_darwin_amd64"
      binary "netdoc_1.7.1_darwin_amd64", target: "netdoc"
    end
    on_arm do
      sha256 "2b6d1fc2d15a8076132bb94049015ade231b1d1565bfc2b3bb3304b6e2bec4ff"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_darwin_arm64"
      binary "netdoc_1.7.1_darwin_arm64", target: "netdoc"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba49fab13360ec4eeb713b395bd17395ce8827faf37152ad53e59eaf72499489"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_linux_amd64"
      binary "netdoc_1.7.1_linux_amd64", target: "netdoc"
    end
    on_arm do
      sha256 "e5b41f3cb95502e8771d8cd69156d2ed6cc565f62903a036d9998296c9df801c"
      url "https://github.com/heymaikol/network-doctor/releases/download/v#{version}/netdoc_#{version}_linux_arm64"
      binary "netdoc_1.7.1_linux_arm64", target: "netdoc"
    end
  end

  name "network-doctor"
  desc "Terminal UI that diagnoses network connectivity and explains where the connection breaks"
  homepage "https://github.com/heymaikol/network-doctor"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
